cabal-version: 3.0
name: jbini
version: 0.1.0.0
build-type: Simple

common warnings
  ghc-options: -Wall -Wno-name-shadowing -Wno-unused-do-bind
  default-extensions:
      BlockArguments
    , DerivingStrategies
    , GeneralizedNewtypeDeriving
    , LambdaCase
    , NamedFieldPuns
    , RecordWildCards

library
  import: warnings
  exposed-modules: Jbini
  other-modules:
      Jbini.Evaluate
    , Jbini.Parse
    , Jbini.Syntax
    , Jbini.TypeCheck
  hs-source-dirs: src
  default-language: Haskell2010
  build-depends:
      base >=4.20 && <5
    , containers
    , directory
    , filepath
    , megaparsec
    , time
    , transformers

executable jbini
  import: warnings
  main-is: Main.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
      base >=4.20 && <5
    , containers
    , directory
    , filepath
    , jbini

test-suite jbini-test
  import: warnings
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  default-language: Haskell2010
  build-depends:
      base >=4.20 && <5
    , containers
    , directory
    , jbini
