cabal-version: 3.0
name: tung
version: 0.1.0.0
build-type: Simple
extra-source-files: .bookhoard-membership

common warnings
  ghc-options: -O2 -Wall -Wno-name-shadowing -Wno-unused-do-bind
  default-extensions:
      BlockArguments
    , DerivingStrategies
    , GeneralizedNewtypeDeriving
    , LambdaCase
    , ImportQualifiedPost
    , NamedFieldPuns
    , RecordWildCards
    , TupleSections

library
  import: warnings
  exposed-modules: Tung
  other-modules:
      Tung.Core
    , Tung.Bookhoard.Files
    , Tung.Coverage
    , Tung.Diagnostic
    , Tung.Evaluate
    , Tung.Format
    , Tung.Embed
    , Tung.Import
    , Tung.Identity
    , Tung.Metadata
    , Tung.Bookhoard
    , Tung.Name
    , Tung.Parse
    , Tung.Primitive
    , Tung.Project
    , Tung.Syntax
    , Tung.Token
    , Tung.Type
    , Tung.Validate
    , Tung.Web
  hs-source-dirs: src
  default-language: Haskell2010
  build-depends:
      base >=4.20 && <5
    , bytestring
    , containers
    , directory
    , filepath
    , megaparsec
    , network >=3.1 && <4
    , process
    , stm
    , template-haskell
    , text
    , time
    , transformers

executable tung
  import: warnings
  main-is: Main.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
      base >=4.20 && <5
    , containers
    , filepath
    , tung

benchmark tung-benchmark
  import: warnings
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: benchmark
  ghc-options: -rtsopts -with-rtsopts=-T
  default-language: Haskell2010
  build-depends:
      base >=4.20 && <5
    , containers
    , directory
    , filepath
    , process
    , tung

test-suite tung-test
  import: warnings
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  default-extensions: MultilineStrings
  other-modules:
      Test.Core
    , Test.Diagnostic
    , Test.Evaluate
    , Test.Format
    , Test.Harness
    , Test.Import
    , Test.Integration
    , Test.Bookhoard
    , Test.Name
    , Test.Parse
    , Test.Project
    , Test.Token
    , Test.Type
    , Test.Validate
  default-language: Haskell2010
  build-depends:
      base >=4.21 && <5
    , bytestring
    , containers
    , directory
    , filepath
    , network >=3.1 && <4
    , QuickCheck
    , time
    , tung
